# Generated by Django 4.1.9 on 2023-05-12 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('triapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('rental_mode', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('sleeping_arrangement', models.CharField(max_length=255)),
                ('washrooms', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to='property/')),
                ('nearest_station_airport', models.CharField(max_length=255)),
                ('nearest_station_bus', models.CharField(max_length=255)),
                ('nearest_station_train', models.CharField(max_length=255)),
                ('photos', models.TextField()),
                ('amenities', models.CharField(max_length=255)),
                ('preferred_guest', models.CharField(max_length=255)),
                ('length_of_stay', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
