# Generated by Django 4.1.9 on 2023-05-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triapp', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_userdata',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
