# Generated by Django 4.2.1 on 2023-05-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triapp', '0004_rename_amenities_property_beds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='locationState',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
