# Generated by Django 4.2.1 on 2023-05-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triapp', '0007_property_bank_details_alter_property_aadhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
